name = "NewtonsMethod"
uuid = "38970c50-ed06-11e8-28c9-19b179c58e3c"
authors = ["AliKarimirad <ali.karimirad1369@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
